name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Wine and Xvfb
        run: |
          sudo apt update
          sudo apt install -y ninja-build gcc g++ gcc-multilib g++-multilib libclang-dev clang lld

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Download MSVCRT40.DLL
        run: wget "https://discmaster.textfiles.com/file/858/boot-disc-1998-05.iso/Utils/Online/Internet%20Explorer%204.01/IE4MFC40.CAB/MSVCRT40.DLL" -O compilers/msvc420/bin/MSVCRT40.DLL

      - name: make
        run: |
          make TEACHER.EXE

  compare-similarity:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Install Wine and Xvfb
        run: |
          sudo apt update
          sudo apt install -y ninja-build gcc g++ gcc-multilib g++-multilib libclang-dev clang lld

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Download MSVCRT40.DLL to temp
        run: wget "https://discmaster.textfiles.com/file/858/boot-disc-1998-05.iso/Utils/Online/Internet%20Explorer%204.01/IE4MFC40.CAB/MSVCRT40.DLL" -O /tmp/MSVCRT40.DLL

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          submodules: true

      - name: Install MSVCRT40.DLL
        run: cp /tmp/MSVCRT40.DLL compilers/msvc420/bin/MSVCRT40.DLL

      - name: Generate report on Base
        run: make report > report-before.txt

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install MSVCRT40.DLL
        run: cp /tmp/MSVCRT40.DLL compilers/msvc420/bin/MSVCRT40.DLL

      - name: Generate report on PR
        run: make report > report-after.txt

      - name: Compare reports
        run: |
          echo "Similarity report diff:"
          diff -u report-before.txt report-after.txt || true
